baseURL = "https://int02h.ru/"
languageCode = "en-us"
title = "Daniil Popov"
theme = "hugo-coder"

[params]
	author = "Daniil Popov"
	info = "Android engineer and musician"
	avatarurl = "images/avatar.jpg"
    favicon_16 = "images/favicon-16x16.png"
    favicon_32 = "images/favicon-32x32.png"

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    url = "https://github.com/int02h/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    url = "https://twitter.com/int02h/"

[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 1
    url = "https://medium.com/@int02h"